export const aiProjectsData = [
  {
    id: 1,
    name: 'AutoGPT',
    author: 'Significant-Gravitas',
    full_name: 'Significant-Gravitas/AutoGPT',
    description: '一个强大的平台，用于创建、部署和管理持续运行的AI智能体，自动化复杂工作流。提供Agent Builder、工作流管理和部署控制功能。',
    key_features: ['可视化Agent构建器', '工作流编排与管理', '持续运行的AI智能体', '监控与分析仪表板'],
    stars: 175205,
    forks: 45698,
    tech_stack: ['Python', 'TypeScript', 'Docker', 'FastAPI'],
    github_url: 'https://github.com/Significant-Gravitas/AutoGPT',
    license: 'MIT',
    category: 'Multi-Agent 框架'
  },
  {
    id: 2,
    name: 'MetaGPT',
    author: 'FoundationAgents',
    full_name: 'FoundationAgents/MetaGPT',
    description: '多智能体框架，模拟软件公司结构，将不同角色分配给GPT形成协作实体。输入一行需求，输出完整软件工程产物。',
    key_features: ['软件公司多角色模拟', 'Code = SOP(Team)', '自然语言编程', 'Data Interpreter'],
    stars: 61919,
    forks: 7299,
    tech_stack: ['Python', 'Node.js', 'pnpm'],
    github_url: 'https://github.com/FoundationAgents/MetaGPT',
    license: 'MIT',
    category: 'Multi-Agent 框架'
  },
  {
    id: 3,
    name: 'LangChain',
    author: 'langchain-ai',
    full_name: 'langchain-ai/langchain',
    description: '构建LLM驱动的智能体和应用的主流框架。通过可互操作组件和第三方集成简化AI应用开发。',
    key_features: ['700+ 集成生态', '模块化组件架构', 'LangGraph工作流', '生产级监控'],
    stars: 127128,
    forks: 20904,
    tech_stack: ['Python', 'TypeScript'],
    github_url: 'https://github.com/langchain-ai/langchain',
    license: 'MIT',
    category: 'LLM 应用框架'
  },
  {
    id: 4,
    name: 'AutoGen',
    author: 'Microsoft',
    full_name: 'microsoft/autogen',
    description: '微软推出的编程框架，用于构建代理式AI应用。支持创建可定制、可对话的智能体，集成LLM、工具和人工监督。',
    key_features: ['多智能体对话框架', '人工在环工作流', '代码执行支持', '分层可扩展架构'],
    stars: 54698,
    forks: 8234,
    tech_stack: ['Python', '.NET', 'C#'],
    github_url: 'https://github.com/microsoft/autogen',
    license: 'CC-BY-4.0',
    category: 'Multi-Agent 框架'
  },
  {
    id: 5,
    name: 'CrewAI',
    author: 'crewAIInc',
    full_name: 'crewAIInc/crewAI',
    description: '编排角色扮演自主AI智能体的框架。通过培养协作智能，使智能体无缝协作完成复杂任务。',
    key_features: ['角色驱动智能体设计', 'Crews自主协作', 'Flows精确控制', '事件驱动工作流'],
    stars: 44413,
    forks: 5957,
    tech_stack: ['Python', 'UV'],
    github_url: 'https://github.com/crewAIInc/crewAI',
    license: 'MIT',
    category: 'Multi-Agent 框架'
  },
  {
    id: 6,
    name: 'LlamaIndex',
    author: 'run-llama',
    full_name: 'run-llama/llama_index',
    description: '领先的文档智能体和OCR平台。数据框架用于构建LLM驱动的智能体应用，支持160+数据源连接。',
    key_features: ['160+ 数据连接器', '高级RAG工作流', '文档智能体', '多模态支持'],
    stars: 47102,
    forks: 6860,
    tech_stack: ['Python', 'TypeScript'],
    github_url: 'https://github.com/run-llama/llama_index',
    license: 'MIT',
    category: '数据智能体框架'
  },
  {
    id: 7,
    name: 'Dify',
    author: 'langgenius',
    full_name: 'langgenius/dify',
    description: '开源LLM应用开发平台。直观的界面结合AI工作流、RAG管道、智能体能力、模型管理和可观测性功能。',
    key_features: ['可视化AI工作流', '高质量RAG引擎', '多模型无缝切换', '智能体框架'],
    stars: 129954,
    forks: 20233,
    tech_stack: ['Python', 'TypeScript', 'React'],
    github_url: 'https://github.com/langgenius/dify',
    license: 'Apache-2.0',
    category: 'LLM 应用平台'
  },
  {
    id: 8,
    name: 'OpenHands',
    author: 'All-Hands-AI',
    full_name: 'All-Hands-AI/OpenHands',
    description: '开源AI软件开发智能体。通过自然语言指令执行各种软件开发任务，致力于少写代码多出成果。',
    key_features: ['自然语言交互式开发', '全栈开发自动化', '多语言支持', 'SWE-bench领先'],
    stars: 54040,
    forks: 6092,
    tech_stack: ['Python', 'Docker', 'React'],
    github_url: 'https://github.com/All-Hands-AI/OpenHands',
    license: 'MIT',
    category: 'AI 编程智能体'
  },
  {
    id: 9,
    name: 'Flowise',
    author: 'FlowiseAI',
    full_name: 'FlowiseAI/Flowise',
    description: '拖放式UI框架，用于构建定制化LLM流程。基于LangChain，通过可视化界面快速构建和部署AI应用。',
    key_features: ['可视化流程构建器', '拖放式界面', '自定义LLM集成', 'API自动生成'],
    stars: 47784,
    forks: 23485,
    tech_stack: ['TypeScript', 'Node.js', 'React'],
    github_url: 'https://github.com/FlowiseAI/Flowise',
    license: 'Apache-2.0',
    category: '低代码 LLM 平台'
  },
  {
    id: 10,
    name: 'LangGraph',
    author: 'langchain-ai',
    full_name: 'langchain-ai/langgraph',
    description: '构建有状态、多智能体应用的低层框架。基于图的结构支持循环、条件分支和持久化状态。',
    key_features: ['有向图工作流', '支持循环和重试', '人工在环检查点', '长期记忆支持'],
    stars: 12428,
    forks: 2080,
    tech_stack: ['Python', 'TypeScript'],
    github_url: 'https://github.com/langchain-ai/langgraph',
    license: 'MIT',
    category: '智能体编排框架'
  },
  {
    id: 11,
    name: 'DSPy',
    author: 'stanfordnlp',
    full_name: 'stanfordnlp/dspy',
    description: '斯坦福开发的编程框架，用于优化语言模型使用。通过声明式语言模型调用转换为自优化管道。',
    key_features: ['声明式LM编程', '自动提示优化', '自优化管道', '少样本学习优化'],
    stars: 24131,
    forks: 1857,
    tech_stack: ['Python'],
    github_url: 'https://github.com/stanfordnlp/dspy',
    license: 'MIT',
    category: 'LLM 编程框架'
  },
  {
    id: 12,
    name: 'CAMEL',
    author: 'camel-ai',
    full_name: 'camel-ai/camel',
    description: '最早基于LLM的多智能体框架之一，专注于探索智能体的缩放定律。通过角色扮演让智能体协作解决任务。',
    key_features: ['角色扮演框架', 'Workforce自动化', 'OASIS世界模拟', 'RAG管道支持'],
    stars: 14875,
    forks: 1638,
    tech_stack: ['Python'],
    github_url: 'https://github.com/camel-ai/camel',
    license: 'Apache-2.0',
    category: '多智能体研究框架'
  }
]
